### ISSUE TITLE
Title/Intro section

### ISSUE THREAD

**Issue by mikkelertbjerg** [DavidCarl/UFO#1]
- The title itself could you use some work, it's a blog, give it a catchy title.
- The overall introduction is alright, but could be a stand alone section to create a better overview.
- There's no abstract
- There's no problem statement
- As a result we're very unlcear of the scope of this blog post?
- It appears as a description of an old school project, not an actual discussion.
- You mention SQL and Greb, but provide no references, if i'm unfarmillar with either or both concepts I'm already lost as a reader.

**Comment by Fridai1** [comment]
- You mention an old school project, but you don't link your own repo with your solution, nor the project text. Since you are basing your blog post on this assignment, it would be nice to be able to gain some insight into this assignment.

**Comment by DavidCarl** [comment]
Closed since these things has been resolved
