### ISSUE TITLE
MySQL Section

### ISSUE THREAD

**Issue by mikkelertbjerg** [DavidCarl/UFO#2]
- What exactly is MySQL Full Text Indexing, there's a clear lack of references.
- It's not descriped either in the text
- Why would MSQL FTI be able to solve this problem?
- We understand the description of the task at hand, but as there's no scope for the blog, we're not sure what make of this information.
- Section is ended rather apruptly? Why exactly did you stop experimenting with MySQL FTI?

**Comment by DavidCarl** [comment]
Closed since we are deleting MySQL completely! But thanks for the review :)
