### ISSUE TITLE
GREP Section

### ISSUE THREAD

**Issue by mikkelertbjerg** [DavidCarl/UFO#3]
- What exactly is Grep? Give us a reference
- Why is is Grep a viable alternative to MySQL TFI?
- What is the 'l' option? Give us a reference.
- Why exactly is the 'l' option chosen? Are there alternatives?
- "Nice improvement", you could easily make this more concrete or more sientific by giving us the numbers: i.e "decreasing the search time by 16 seconds, makes our query x% faster" 
- What is the 'w' option? Give us a reference.
- Why is the 'w' option chosen? Are there alternatives?
- You mention there's a difference in searching london with a captial 'L', why is this the case?

**Comment by DavidCarl** [comment]
- [x] What exactly is Grep? Give us a reference

This has been added
- [x] Why is is Grep a viable alternative to MySQL TFI?

MySQL has been removed so this is also solved
- [x] What is the 'l' option? Give us a reference.

Further explanation and link to man page
- [ ] Why exactly is the 'l' option chosen? Are there alternatives?


- [x] "Nice improvement", you could easily make this more concrete or more sientific by giving us the   numbers: i.e "decreasing the search time by 16 seconds, makes our query x% faster" 

Changed wording to fix this
- [x] What is the 'w' option? Give us a reference.

Further explanation and link to man page
- [ ] Why is the 'w' option chosen? Are there alternatives?


- [x] You mention there's a difference in searching london with a captial 'L', why is this the case?

removed mention, but added a tiny section about case sensitivity with reference

**Comment by DavidCarl** [comment]
Closed since these things has been resolved
