### ISSUE TITLE
GREB Benchmark section

### ISSUE THREAD

**Issue by mikkelertbjerg** [DavidCarl/UFO#4]
- Is greb something else, or just an unfornate typeo?
- Provide a reference to the run_time_data_folder
- How exactly did you obtain the data?
- Discuss pitfalls in the way you did it?
- Discuss alternative methods, or argue why you did it the way you did it?
- The graph itself needs a bit of explanation, and can't stand alone, which is a shame.
- What is xargs? Give us a reference
- What is find? Give us a reference
- Why is the thread break point at one? I.e why is not worth it, to use two?
- There's a whole discussion lost on the threading aspect, which you should also provide a reference for
- What are the pros and cons of single/multi threading, besides speed?

**Comment by DavidCarl** [comment]
Closed since these things has been resolved
