### ISSUE TITLE
Reproduce section

### ISSUE THREAD

**Issue by mikkelertbjerg** [DavidCarl/UFO#5]
- You don't mention any dependencies or installation guides?
- Do you have any dos and donts, what did you experience? What are your reccomendations?
- Are there any pitfalls to be aware of?
- Do you reccomend testing on a VM like yourselves? What are the pros/cons of this?
- You clearly discovered some spec requirements, do you have any reccomendations?

**Comment by DavidCarl** [comment]
Should have fixed these that are interesting / not 'stupid' waste of lines. Ex, we said earlier to run in a Unix system so theres no reason to say you need to run it in a Unix system again.

Some of these are no longer relevant since MySQL has been deleted.
