### ISSUE TITLE
Performance levels

### ISSUE THREAD

**Issue by mikkelertbjerg** [DavidCarl/UFO#8]
**OVERVIEW: 2 POINTS** 
- No abstract or problem statement. We're not sure what we are trying to achieve other than solving a school assignement?

**RELIABLE DATA:  1 POINTS** 
- Not a single reference.

**CONSTRAINTS: 2 POINTS** 
- The SQL section stops after you run out of data, and you don't provide any info on why you ran out of data, and what you tried to fix it?
- You then include grep/greb, which you build up nicely, but you throw around with a lot of terms, and never discuss why you use certain options or what said options actually does.
- There's no justification to why you went with the options you did, are there alternatives? the reader is completely blindsided, unless they are already experts in greb?

**CRITERIA: 3 POINTS**
- You provide a decent graph although it needs quite a bit of explanation, but you never discuss error margins, alternatives or the like.
- Again a few terms are introduced or assumoptions made without any explanation?

**WORK: 2 POINTS** 
- You compare the two 'topics' on a I think basis, which leaves the reader with very few answers. You say you would use Full Text Index if you were to do it again because someone achieved good performance, but never talk about the challanges it might bring. Is there maybe a third option?
- Could you have done something differently with greb?

**Comment by DavidCarl** [comment]
Closed since I think we need to close all issues?
